parameters:
  api_url: 'http://localhost/'
  file_path: %base_path%/files/
  log_file_path: %base_path%/client.log
  path_to_blender: 'blender'
  image_formats:
    PNG: png
    JPEG: jpg

services:
  console:
    class: Symfony\Component\Console\Application
    calls:
      - [ add, [@run_command] ]
      - [ setDefaultCommand, ['run'] ]

  run_command:
    class: MoSchulze\BlenderFarmClient\Command\RunCommand
    calls:
      - [ setClient, [@client] ]

  client:
    class: MoSchulze\BlenderFarmClient\Client
    calls:
      - [ setApiUrl, [%api_url%] ]
      - [ setFileRepository, [@file_repository] ]
      - [ setLogger, [@logger] ]
      - [ setBlender, [@blender] ]

  file_repository:
    class: MoSchulze\BlenderFarmClient\FileRepository
    calls:
      - [ setFileBasePath, [%file_path%] ]

  blender:
    class: MoSchulze\BlenderFarmClient\Blender
    calls:
      - [ setPathToBlender, [%path_to_blender%] ]
      - [ setFileRepository, [@file_repository] ]
      - [ setImageFormats, [%image_formats%] ]

  logger:
    class: Monolog\Logger
    arguments: ['BlenderFarmClient']
    calls:
      - [ pushHandler, [@log_handler] ]

  log_handler:
    class: Monolog\Handler\RotatingFileHandler
    arguments: [ %log_file_path%, 7 ]