imports:
    - { resource: 'parameters.yml' }

parameters:
  image_formats:
    PNG: png
    JPEG: jpg

services:
  console:
    class: Symfony\Component\Console\Application
    calls:
      - [ add, [@run_command] ]
      - [ add, [@test_command] ]
      - [ setDefaultCommand, ['run'] ]

  run_command:
    class: MoSchulze\BlenderFarmClient\Command\RunCommand
    calls:
      - [ setClient, [@client] ]

  test_command:
    class: MoSchulze\BlenderFarmClient\Command\TestCommand
    calls:
      - [ setApi, [@api] ]
      - [ setBlender, [@blender] ]
      - [ setFilePath, [%file_path%] ]
      - [ setLogPath, [%log_file_path%] ]

  api:
    class: MoSchulze\BlenderFarmClient\Api
    arguments: [%api_url%]

  client:
    class: MoSchulze\BlenderFarmClient\Client
    calls:
      - [ setApi, [@api] ]
      - [ setFileRepository, [@file_repository] ]
      - [ setLogger, [@logger] ]
      - [ setBlender, [@blender] ]

  file_repository:
    class: MoSchulze\BlenderFarmClient\FileRepository
    calls:
      - [ setFileBasePath, [%file_path%] ]

  blender:
    class: MoSchulze\BlenderFarmClient\Blender
    calls:
      - [ setPathToBlender, [%path_to_blender%] ]
      - [ setFileRepository, [@file_repository] ]
      - [ setImageFormats, [%image_formats%] ]
      - [ setApi, [@api] ]
      - [ renderOnGpu, [%cycles_use_gpu%] ]

  logger:
    class: Monolog\Logger
    arguments: ['BlenderFarmClient']
    calls:
      - [ pushHandler, [@log_handler] ]

  log_handler:
    class: Monolog\Handler\RotatingFileHandler
    arguments: [ %log_file_path%, 7 ]
    calls:
      - [ setFormatter, [@log_formatter] ]

  log_formatter:
    class: Monolog\Formatter\LineFormatter
    arguments: [ "[%%datetime%%] %%level_name%%: %%message%%\n", 'Y-m-d H:i:s' ]